# Generated by Django 5.2 on 2025-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('salario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
